### PR TITLE
user-interface 

### PR DESCRIPTION
**Pull request by ashraffares**
adding two methods
new_player: get player choice x or o 
board: display board and get a player move

### CODE REVIEW

**Review by SmithVyne — CHANGES_REQUESTED** [review]
Changes Required 👍 👍 
Hello, good work with your current progress on this project, but you need to complete the other requirements for this milestone:

[REQUIRED] game displays the board after the player move (without computing which spots on the board are taken)
[REQUIRED] game informs player if the selected move is a winning move (without computing the winning move)
[REQUIRED] game informs player if the selected move is a draw move (without computing draw)
[REQUIRED] game repeats all actions for the next player's move

You can reach out to me on slack, **@smithvyne**, to clarify any parts you do not understand.

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

### Hey @ashraffares & @uwadonat, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. However, there are a few issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [ ] The game tells which player turn it is (without computing who the winner is).
- [ ] game informs player if the selected move is invalid (without computing what an invalid move is). Your game instead terminates.
- [ ] game informs player if the selected move is a winning move (without computing the winning move).
- [ ] game informs player if the selected move is a draw move (without computing draw).
-  You can add methods for win and draw to help you with some of the above requirements.
```

game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end

```

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Comment by ashraffares** [comment]
added 
draw method
win method
player_turn method
display message for invalid inputs

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

### Hey @ashraffares & @uwadonat, 👋🏽 
**Well-done lads and thanks for implementing the changes requested earlier on**. However, there are a few more issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [ ] Valid inputs should only be integers 1 - 9. Everything else should be considered invalid. Kindly adjust your `get_inputs` method to cater to everything else. The game terminates once I enter `abc` as my input. It should inform the player that it is an invalid input.

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Comment by mke2111** [comment]
# STATUS: INVALID 🔴 

### Kindly fix the failing linters.

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇 
### Hi there Team ✋🏽 

Congratulations on successfully completing this milestone. You can go ahead and merge this pull request and then move on to the next milestone. 
 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Pull request merged**
