### PR TITLE
Testing Tic-Tac-Toe project

### PR DESCRIPTION
**Pull request by elyor-doniyorov**
In this testing project we:

- installed RSpec to our project
- added spec file
- tested methods if they are working correctly

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi team!
Good job on this milestone:clap::clap:. The codebase is clean and easy to understand. However, we need to make a few changes to get the project working and approved:muscle:**.

**Mandatory requirements**

- [ ] Currently, the readme is all about how to play the game, and not how to test the game. Kindly rewrite it to demonstrate how to test the game.

- [ ] When I run rspec on the root directory of the rspec_test branch, no test runs. But when I renamed the test.rb to test_spec.rb. The test runs. Kindly up this.

- [ ] We currently have only positive test case scenarios. Kindly also add negative tests cases.

- [ ] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. The .rubocop.yml config is currently altered. Check this screen-shot for reference: https://imgur.com/a/a0bZuWp.

Kindly copy  and use a fresh config using this link: https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml

Make the above changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond
Happy Coding:blush:
Eric Enaburekhan

**Comment by ashraffares** [comment]
- change readme to include how to run the test
- adding more test cases
- changeset the config file to the original

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hello Team,

Thank you for submitting the Pull Request. You have made all the requested changes. 😄 

Please submit the project and move with your next project. 

Looking forward to seeing your next project soon. 🙈 

**Best,
Arslan Bisharat**

**Comment by elyor-doniyorov** [comment]
Thanks for the review!

**Pull request merged**
