### PR TITLE
milestone3 game logic

### PR DESCRIPTION
**Pull request by ashraffares**
methods implemented 
win method decides the winning moves in the game it covers all the possible causes for win
draw method display draw if at the end of the moves no one wins

### CODE REVIEW

**Comment by smcommits** [comment]
@ashraffares 
Friendly reminder: You should make sure that your repo looks professional before review.

Your **PR message** doesn't provide a good summary of your work in this milestone. Having as much contextual information associated with the PR is extremely helpful for getting a better review. 

Your **commit messages* are non-descriptive. Writing good commit messages is an important skill when working in collaboration. It provides other developers with an understanding of the changes made and why the changes were necessary.

Please read the lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).

This Code Review Request will be marked as invalid in your Dashboard, as maintaining a  professional repo is required to get a code review (please refer to the link above). So, please submit a new one once you are ready!

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are some changes required, please check the comments below._

- ### To Highlight
  - [x] Nice job implementing the previous feedback 💯
  - [x] The project follows Git flow 💯
- ### To Improve
  - [x] [MANDATORY] The project uses at least two classes (Usually it uses three: Game, Board, and Player). The code of the project should be logically divided between classes. 
Capture4

  


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Comment by ashraffares** [comment]
- split game methods into two classes

- class Settings have 

. board method :  display the board.
. flip_user : which change the turn to play for the user

-class Player have 

. game_name : welcome message to the game.
. player_sign : give player1 sign x && player 2 sign o.
. sign_Validate : check if the sign x or o and return true or false.
. move_validate : check if the player moves from 1 to 9 and return true or false.
. index_taken : check if the move from 1 to 9 taken before return true or false.
.wins : check the wining cases and return true of false

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
